const URLS = {
  BASE_URL: "http://35.154.198.31:8080/",
  BASE_URL_V2: "http://35.154.198.31:8090/",
  GOOGLE_REGISTER: "/elga-roma/user/signIn",
  API_FETCH_USER_CATEGORY: "elga-roma/category/all",
  API_ASSIGN_USER_IDENTITY: "elga-roma/social/instagram",
  API_ASSIGN_AGENCY_DETAILS: "elga-roma/agency",
  API_SAVE_INSTAGRAM_DETAILS: "elga-roma/social/instagram/",
  API_FETCH_ADMIN_CATEGORY: "elga-roma/category/get/administrator",
  API_ASSIGN_SUBCATEGORIES: "elga-roma/user/assign-meta",
  API_ADD_CITATION: "/elga-roma/comment",
  API_FETCH_USER_PROFILE: "elga-roma/user",
  API_FETCH_USER_CITATION: "elga-roma/comment",
  API_FETCH_DISCOVER_CATEGORIES: "elga-roma/category/all/discover",
  API_FETCH_DISCOVER_USER: "elga-roma/user/all/category",
  API_FETCH_TRENDING_USER: "elga-roma/user/all",
  API_CREATE_COLLAB: `elga-roma/project/create`,
  API_GET_COLLAB: `/elga-roma/project/collaborators`,
  API_FETCH_DISCOVER_USER_FROM_SUBCATEGORY: "elga-roma/user/all/subcategory",
  API_FETCH_USER_META: (userId) =>
    `elga-roma/social/instagram/meta-data/${userId}`,
  API_GET_PROJECT_LIST: "elga-roma/project/all",
  API_GET_PROJECT_SEARCH: "elga-roma/project/search",
  API_FETCH_SAVED: `/elga-roma/saved`,
  API_SAVE_ENTITY: (entityId) => `/elga-roma/save/unSave/${entityId}`,
  API_FETCH_USER_INSTAGRAM: `/elga-roma/user/media`,
  API_GET_PROJECT_DETAIL_LIST: "/elga-roma/project/collaboration",
  API_ACCEPT_PROJECT: "/elga-roma/project/accept",
  API_REJECT_PROJECT: "/elga-roma/project/decline",
  API_WITHDRAW_PROJECT: "/elga-roma/project/withdraw",
  API_GET_CIRCLE_DATA: `/elga-roma/circle/all`,
  API_DELETE_CIRCLE_DATA: `/elga-roma/circle/close`,
  API_UPDATE_USER_PROFILE: '/elga-roma/user',
  API_SEND_CIRCLE_REQ: '/elga-roma/circle/send',
  API_ADD_MEMBERS: '/elga-roma/project/add-members',
  API_USER_SEARCH: (key) => `elga-roma/user/search/${key}`,
  API_ASSIGN_LOCATION: `/elga-roma/user/location`,
  API_ACCEPT_CIRCLE_DATA: `/elga-roma/circle/accept`,
  API_UPDATE_MEDIA: ` /elga-roma/user/upload-media`,
  API_GET_MEDIA: `/elga-roma/user/media`,
  API_ADD_LINK: `/elga-roma/link`,
  API_GET_POPULAR_GENRE: `/elga-roma/genre/all`,
  API_GENRE_SEARCH: `/elga-roma/genre/search`,
  API_GENRE_ASSIGN: `/elga-roma/genre/assign`,
  API_CATEGORY_SEARCH: `/elga-roma/category/search`,
  API_UPLOAD_PHOTO: `elga-roma/user/upload-media`,
  API_LINKS: "elga-roma/link",
  API_REMOVE_MEMBERS: (action) => `/elga-roma/project/chat/${action}`,
  API_GET_CIRCLE_SEARCH_DATA: "/elga-roma/circle/search",
  API_REGENERATE_TOKEN: "elga-roma/token/regenerate",
  API_UPDATE_ELASTIC_SEARCH: "/elga-roma/user/elasticsearch",
  API_LINKS_COUNTER: "/elga-roma/link/increment-count",
  API_IS_VISITED_PROFILE: "/elga-roma/user/view",
  API_COLLAB_COUNT:(username) => `elga-roma/project/collaborators/count/${username}`,
  API_FETCH_SAVED_SEARCH: (entity) => `/elga-roma/saved/search`,
  API_GET_NOTIFICATION:`elga-roma/user/notification`,
  API_GET_ARCHIVE_CHAT: `elga-roma/project/close`,
  API_REWARD:`/elga-roma/user/refer`,
  API_DELETE_AGENCY_DETAILS: '/elga-roma/agency',
  API_FETCH_PROFILE_COMPLETION_PERCENTAGE: '/elga-roma/user/profile/percentage',
  API_FETCH_FEED_LIST: '/elga-roma/link/all',
  API_FEED_ACTIVITY: (activity) => `/elga-roma/user/${activity}`,
  API_FEED_DETAILS: (id) => `/elga-roma/link/${id}`
};


export default URLS;

