import { Dimensions, StyleSheet } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import COLORS from "../../../themes/colors";
const Styles = StyleSheet.create({
  container: {
    height: "100%",
    width: "100%",
    justifyContent: "flex-start",
    //flexDirection: "column-reverse",
  },
  toggleBar: {
    width: RFValue(34, 844),
    height: RFValue(6, 844),
    backgroundColor: COLORS.monoGhost500,
    borderRadius: RFValue(20, 844),
    alignSelf: "center",
    marginTop: RFValue(15, 844),
  },

  headerContainer: {
    marginTop: RFValue(-25, 844),
    zIndex: 1,
    height: "20%",
    backgroundColor: COLORS.monoWhite900,
    paddingHorizontal: RFValue(32, 844),
    paddingBottom: RFValue(32, 844),
    borderRadius: RFValue(24, 844),
  },
  titleContainer: {
    marginTop: RFValue(12, 844),
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  titleText: {
    fontFamily: "Poppins_500Medium",
    fontSize: RFValue(16, 844),
    color: COLORS.monoBlack900,
  },
  subtitleContainer: {
    width: "100%",
    marginTop: RFValue(8, 844),
    alignItems: "center",
    flexDirection: "row",
  },
  subtitleText: {
    marginLeft: RFValue(8, 844),
    fontSize: RFValue(14, 844),
    fontFamily: "Poppins_400Regular",
    color: COLORS.monoBlack500,
    alignSelf: "center",
    marginTop: 4,
  },

  descriptionText: {
    marginTop: RFValue(18, 844),
    fontFamily: "Poppins_400Regular",
    fontSize: RFValue(14, 844),
    color: COLORS.monoBlack700,
  },
  innerContainer: {
    paddingHorizontal: RFValue(36, 844),
    paddingTop: RFValue(36, 844),
    paddingBottom: RFValue(12, 844),
    borderTopEndRadius: 24,
    borderTopStartRadius: 24,
    position: "absolute",
    backgroundColor: COLORS.monoWhite900,
    width: "100%",
    // top: RFValue(240, 844),
    bottom: 0,
    height: "78%",
  },
  projectDetailContainer: {
    marginTop: RFValue(20, 844),
  },
  projectInnerContainer: {
    marginTop: RFValue(12, 844),
  },
  detailContainer: {
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "row",
    marginBottom: RFValue(16, 844),
  },
  detailTitle: {
    fontFamily: "Poppins_700Bold",
    fontSize: RFValue(12, 844),
    color: COLORS.primaryTeal500,
    lineHeight: RFValue(32, 844),
  },
  detailInfo: {
    fontFamily: "Poppins_600SemiBold",
    fontSize: RFValue(12, 844),
    color: COLORS.monoBlack500,
    lineHeight: RFValue(32, 844),
    letterSpacing: 0.25,
  },
  bottomContainer: {
    width: "100%",
    position: "absolute",
    zIndex: 10,
    backgroundColor: COLORS.monoWhite900,
    paddingVertical: RFValue(28, 844),
    paddingHorizontal: RFValue(36, 844),
    bottom: 0,
  },
  buttonWrapper: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginBottom: RFValue(12, 844),
  },
  saveButton: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    borderRadius: RFValue(12, 844),
    height: RFValue(56, 844),
    paddingHorizontal: RFValue(10, 844),
    backgroundColor: COLORS.monoGhost500,
    width: "22%",
  },
  categoryContainer: {
    margin: RFValue(17, 844),
    height: RFValue(40, 844),
    left: RFValue(16, 844),
    top: RFValue(32, 844),
  },
  category1: {
    borderRadius: RFValue(12, 844),
    backgroundColor: COLORS.primaryTeal400,
    height: RFValue(20, 844),
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 4,
  },
  category1Text: {
    color: COLORS.monoWhite900,
    fontSize: RFValue(12, 844),
    fontFamily: "Poppins_400Regular",
    marginHorizontal: RFValue(8, 844),
    marginTop: 1,
  },
  category2: {
    borderRadius: RFValue(12, 844),
    backgroundColor: COLORS.monoGhost500,
    height: RFValue(20, 844),
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 4,
  },
  category2Text: {
    color: COLORS.primaryTeal500,
    fontSize: RFValue(12, 844),
    fontFamily: "Poppins_400Regular",
    marginHorizontal: RFValue(8, 844),
    marginTop: 1,
  },
});
export default Styles;
